---
erlang_package:
  - erlang-base
  - erlang-asn1 
  - erlang-crypto 
  - erlang-eldap 
  - erlang-ftp 
  - erlang-inets
  - erlang-mnesia
  - erlang-os-mon 
  - erlang-parsetools 
  - erlang-public-key
  - erlang-runtime-tools 
  - erlang-snmp 
  - erlang-ssl
  - erlang-syntax-tools 
  - erlang-tftp 
  - erlang-tools 
  - erlang-xmerl

requirements:
  - curl
  - gnupg
  - apt-transport-https

rabbitmq_signing_key: 
  - url: https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA
    dest: "/usr/share/keyrings/com.rabbitmq.team.gpg"


rabbitmq_repos:
  - name: rabbitmq-erlang-ppa1
    uris: "https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-erlang/deb/{{ ansible_distribution | lower }}"
    signed_by: "https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-erlang.E495BB49CC4BBE5B.key"
  - name: "rabbitmq-erlang-ppa2"
    uris: "https://ppa2.rabbitmq.com/rabbitmq/rabbitmq-erlang/deb/{{ ansible_distribution | lower }}"
    signed_by: "https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-erlang.E495BB49CC4BBE5B.key"
  - name: "rabbitmq-server-ppa1"
    uris: "https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-server/deb/{{ ansible_distribution | lower }}"
    signed_by: "https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-server.9F4587F226208342.key"
  - name: "rabbitmq-server-ppa2"
    uris: "https://ppa2.rabbitmq.com/rabbitmq/rabbitmq-server/deb/{{ ansible_distribution | lower }}"
    signed_by: "https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-server.9F4587F226208342.key"