---

- name: Устанавливаем необходимые пакеты
  ansible.builtin.apt:
    name: "{{ requirements }}"
    state: present
    update_cache: true

- name: Устанавливаем дополнительный пакет для Debian
  ansible.builtin.apt:
    name: debian-archive-keyring
    state: present
  when: ansible_distribution | lower == "debian"

- name: Добавляем репозиторий
  ansible.builtin.deb822_repository:
    name: "{{ gitlab_repo_filename }}"
    types: deb
    uris: "https://packages.gitlab.com/gitlab/gitlab-ce/{{ ansible_distribution | lower }}"
    suites: "{{ ansible_distribution_release }}"
    components: main
    signed_by: "{{ gitlab_keys.url }}"

- name: Установка gitlab
  environment:
    GITLAB_ROOT_EMAIL: "{{ gitlab_root_email }}"
    GITLAB_ROOT_PASSWORD: "{{ gitlab_root_password }}"
    EXTERNAL_URL: "{{ external_url }}"
  ansible.builtin.apt:
    name: gitlab-ce
    state: present
    update_cache: true
