---
- name: Restart Prometheus
  community.docker.docker_container:
    name: prometheus
    state: started
    restart: true

- name: Restart Alertmanager
  community.docker.docker_container:
    name: alertmanager
    state: started
    restart: true

- name: Restart Docker Compose Stack
  ansible.builtin.command:
    cmd: docker-compose -f /home/pipeline/monitoring/docker-compose.yml up -d
    chdir: /opt
  changed_when: true