---

- name: Install prerequisite packages
  ansible.builtin.apt:
    name: "{{ requirements }}"
    state: present
    update_cache: true

- name: Ensure /usr/share/keyrings directory
  ansible.builtin.file:
    path: /usr/share/keyrings
    state: directory
    mode: '0755'

- name: Add Team RabbitMQ's main signing key
  ansible.builtin.shell: |
    curl -1sLf "{{ item.url }}" | gpg --dearmor > "{{ item.dest }}"
  args:
    creates: "{{ item.dest }}"
  loop: "{{ rabbitmq_signing_key }}"
  loop_control:
    label: "{{ item.dest | basename }}"


- name: Add RabbitMQ repositories
  ansible.builtin.deb822_repository:
    name: "{{ item.name }}"
    types: deb
    uris: "{{ item.uris }}"
    suites: "{{ ansible_distribution_release }}"
    components: main
    signed_by: "{{ item.signed_by }}"
  loop: "{{ rabbitmq_repos }}"


- name: Install Erlang
  ansible.builtin.apt:
    name: "{{ erlang_package }}"
    state: present
    update_cache: true

- name: Install RabbitMQ
  ansible.builtin.apt:
    name: "rabbitmq-server"
    state: present

- name: Enable and start RabbitMQ service
  ansible.builtin.service:
    name: "rabbitmq-server"
    enabled: true
    state: started

- name: Enable management plugin
  community.rabbitmq.rabbitmq_plugin:
    name: rabbitmq_management
    state: enabled

- name: Create admin user
  community.rabbitmq.rabbitmq_user:
    user: "{{ rabbitmq_admin }}"
    password: "{{ rabbitmq_admin_pass }}"
    login_user: "{{ rabbitmq_admin }}"
    login_password: "{{ rabbitmq_admin_pass }}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    tags: administrator
    state: present
