- hosts: backend
  roles:
    - role: postgres
      vars:
        # By default, all variables are set correctly and do not require changes. You can change them if necessary
        # postgres_version: "17.5"                # PostgreSQL image tag
        # postgres_port: "5532"                   # Default port: 5432
        # postgres_data_dir: "/opt/postgres/data" # Persistent data directory
        # postgres_container_name: "postgres"     # Default container name
        # postgres_db: "pretix"                   # Default database name
        # postgres_user: "pretix"                 # Default database user
        # postgres_password: "*****"              # Default password for database user
        # container_network: "backend"            # Default network for container