- name: reload prometheus
  delegate_to: "{{ groups['monitoring'][0] }}"
  run_once: true
  community.docker.docker_container:
    name: prometheus
    state: started  # Используем 'started' вместо 'restarted'
    restart: yes    # Это обеспечит перезагрузку контейнера