---
- name: Create Blackbox Exporter configuration directory
  ansible.builtin.file:
    path: "{{ blackbox_config_dir }}"
    state: directory
    mode: '0755'
  run_once: true

- name: Deploy Blackbox Exporter configuration
  ansible.builtin.template:
    src: blackbox.yml.j2
    dest: "{{ blackbox_config_dir }}/blackbox.yml"
    mode: '0644'
  run_once: true
  notify: restart blackbox

- name: Run Blackbox Exporter container
  community.docker.docker_container:
    name: blackbox_exporter
    image: "prom/blackbox-exporter:{{ blackbox_version }}"
    state: started
    restart_policy: unless-stopped
    published_ports:
      - "{{ blackbox_port }}:9115"
    volumes:
      - "{{ blackbox_config_dir }}/blackbox.yml:/etc/blackbox_exporter/config.yml:ro"
  run_once: true

- name: Generate Blackbox Exporter file_sd config
  ansible.builtin.template:
    src: blackbox_sd.yml.j2
    dest: "{{ prometheus_file_sd_dir }}/blackbox_targets.yml"
    mode: '0644'
  run_once: true
  delegate_to: "{{ groups['monitoring'][0] }}"
  notify: reload prometheus