---

image: "rabbitmq:3.10.7-management"

container_name: "rabbitmq"

ports:
  - "5672:5672"
  - "15672:15672"

env:
  RABBITMQ_DEFAULT_USER: "pretix"
  RABBITMQ_DEFAULT_PASS: "{{ rabbitmq_password }}"
  RABBITMQ_DEFAULT_VHOST: "pretix_vhost"

data_dir: "/var/lib/rabbitmq"

restart_policy: "unless-stopped"

network_name: "pretix-network"