---
- name: Create directory for Loki storage
  file:
    path: "{{ loki_path }}/data"
    state: directory
    owner: 10001
    group: 10001
    mode: '0700'

- name: Create directory for Loki etc
  file:
    path: "{{ loki_path }}/etc"
    state: directory
    mode: '0755'

- name: Copy Loki configuration
  template:
    src: files/loki-config.yml
    dest: "{{ loki_path }}/etc/local-config.yaml"
    mode: '0644'
  notify:
    - Restart Loki

- name: Create Docker network
  community.docker.docker_network:
    name: "{{ loki_docker_network }}"
    state: present

- name: Run Loki Docker container
  docker_container:
    name: loki
    image: "grafana/loki:{{ loki_version }}"
    ports:
      - "{{ loki_http_port }}:3100"
    volumes:
      - "{{ loki_path }}/data:/loki"
      - "{{ loki_path }}/etc/local-config.yaml:/etc/loki/local-config.yaml"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - name: "{{ loki_docker_network }}"
    restart_policy: unless-stopped
    state: started

- name: Ensure Loki is running
  docker_container_info:
    name: loki
  register: loki_container_info

- name: Display Loki container status
  debug:
    var: loki_container_info.container.State.Status
